rvm:
- 2.2

script:
- RAILS_ENV=test bundle exec rake db:migrate --trace
- bundle exec rake db:test:prepare
- bundle exec rake

notifications:
  hipchat:
    secure: "gQ81ms0fsOtvGrfIpGZUozRPNs12yyNEDK0q7a58609XJJxwHQAUlrjN5fzmmQow+gNS+jX7JFAu4X2gw/6i5AlPlrK+xD3iTP5UYKl3/9bG5gcRCBcBW9IyfgW0nxNuJ4aoNYaSOnE4qhmyiKM2XESHmKwfZ8oxOhh6N4Czk6E="

addons:
  code_climate:
    repo_token:
      secure: "jNpUMrfakaLpLIkpxakyrPzwmYYef9AQPweQTtifTDx63nghBeQMFwHZRsbroZIirpkhAga6P4wFInuys+pZpm7Rr7zFMvtAg3azBsTn91s8nxkSDZyAliE2sA202wBDwS2j/u1y3EVTRrMzmCamN0kxuD8OOwVUgkU6nYhwRDg="

deploy:
  provider: heroku
  api_key:
    secure: JR3iY8pwZJYhrz7QTzYnLehg3+C7G/wNlXTeA09BGkhvMA79enVUIm0B449w+AEqcBXwxT8tONhcUiA06MqjC2oK4KakjFwB8BIbaf9BOyTfyzBuBJ62NoJwj4SqMFEqy9b3cOsEZPJDNG0pNryIh5YDLz09/3JhNR2/+Uqlev4=
  app: 'thawing-basin-3751'
  on:
    repo: dobryakov/hoop
    branch: master
  run:
    - "rake db:migrate"
  strategy: git

